<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Story;
use Doctrine\ORM\EntityRepository;

/**
 * StoryRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class StoryRepository extends EntityRepository
{
    /**
     * @return Story[]
     */
    public function findAllPublicStoryByLastStory()
    {
        return $this->createQueryBuilder("story")
            ->andWhere("story.isPublic = :isPublic")
            ->setParameter("isPublic", true)
            ->leftJoin("story.storyParts", "story_parts")
            ->orderBy("story_parts.createdAt", "DESC")
            ->getQuery()
            ->execute()
        ;
    }
}
