<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Story;

/**
 * StoryPartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoryPartRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllStoryPartsInLast3Months(Story $story)
    {
        return $this->createQueryBuilder("story_part")
            ->andWhere("story_part.story = :story")
            ->setParameter("story", $story)
            ->andWhere("story_part.createdAt > :date")
            ->setParameter("date", new \DateTime("-3 months"))
            ->getQuery()
            ->execute();
    }
}
